openapi: "3.0.0"
info:
    version: 0.1.0
    title: 코어실록 API docs
    description: 코어실록의 API 문서입니다
    license:
        name: MIT
servers:
    - url: http://localhost:3001
paths:
    # signup
    $ref: "./anonymous.yaml"
    # $ref: "./user.yaml"

components:
    responses:
        successResponse:
            description: successful request
            content:
                application/json:
                    schema:
                        type: object
                        properties:
